name: elasticsearch_project
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  pdf: ^3.4.2
  flutter_full_pdf_viewer: ^1.0.6
  path_provider: ^2.0.2
  file_picker: ^3.0.2+2
  flutter_tts: ^3.1.0
  animated_text_kit: ^4.2.1
  flutter_tindercard: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Lato
      fonts:
        - asset: assets/Lato-Regular.ttf
    - family: Lobster
      fonts:
        - asset: assets/Lobster-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

